'use client';

import { motion } from 'framer-motion';
import { Send, Paintbrush } from 'lucide-react';
import { useEffect, useState, useRef } from 'react';
import { cn } from '@/lib/utils';
import GeneratedTattooDisplay from './components/GeneratedTattooDisplay';
import StyleDropdown, { type TattooStyle } from '@/components/StyleDropdown';
import LoginModal from './components/LoginModal';
import PricingModal from './components/PricingModal';
import Sidebar from './components/Sidebar';
import { useAuth } from './AuthContext';
import Background from '@/components/Background';
const backendUrl = import.meta.env.VITE_BACKEND_URL;

type TattooPair = [string, TattooStyle];

// Props for the PromptInput component
interface PromptInputProps {
	onSend?: (data: TattooPair) => void;
	placeholder?: string;
}

// PromptInput Component
function PromptInput({
	onSend = () => {},
	placeholder = 'Describe your dream tattoo...',
}: PromptInputProps) {
	const [input, setInput] = useState('');
	const [isStyleDropdownOpen, setIsStyleDropdownOpen] = useState(false);
	const [selectedStyle, setSelectedStyle] =
		useState<TattooStyle>('Traditional');
	const textareaRef = useRef<HTMLTextAreaElement>(null);
	const MAX_CHARS = 500;

	const handleSubmit = () => {
		if (input.trim()) {
			onSend([input, selectedStyle]); // Get input
			setInput('');
			// Reset height after sending
			if (textareaRef.current) {
				textareaRef.current.style.height = 'auto';
			}
		}
	};

	const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
		if (e.key === 'Enter' && !e.shiftKey) {
			e.preventDefault();
			handleSubmit();
		}
	};

	// Auto-resize textarea based on content
	useEffect(() => {
		if (textareaRef.current) {
			textareaRef.current.style.height = 'auto';
			textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 200)}px`;
		}
	}, [input]);

	const hasContent = input.trim() !== '';

	return (
		<div className="w-full max-w-4xl mx-auto">
			<div className="relative bg-black/5 backdrop-blur-xl border border-black/20 rounded-3xl shadow-2xl shadow-black/10 transition-all duration-300">
				<div className="relative">
					{/* Text Area */}
					<textarea
						maxLength={MAX_CHARS}
						ref={textareaRef}
						value={input}
						onChange={(e) => setInput(e.target.value)}
						onKeyDown={handleKeyDown}
						placeholder={placeholder}
						className="w-full px-6 py-5 bg-transparent border-none outline-none resize-none text-black text-base leading-relaxed placeholder:text-black/40 min-h-[60px] max-h-[200px]"
						style={{ overflow: 'hidden' }}
					/>

					{/* Char counter for Text Area */}
					<div className="absolute bottom-2 right-2 text-xs text-black/40 pointer-events-none">
						{input.length}/{MAX_CHARS}
					</div>
				</div>

				{/* Input Actions Footer */}
				<div className="flex items-center justify-between px-4 py-3 border-t border-black/10">
					<div className="flex items-center gap-2 relative">
						<button
							type="button"
							onClick={() => setIsStyleDropdownOpen(true)}
							className={cn(
								'flex h-9 items-center justify-center gap-2 px-3 rounded-full transition-all',
								selectedStyle
									? 'bg-blue-50 text-blue-600 hover:bg-blue-100'
									: 'text-black/60 hover:text-black hover:bg-black/10',
							)}
							aria-label="Choose Style"
						>
							<Paintbrush className="h-4 w-4" />
							<span className="text-sm font-medium">
								{selectedStyle || 'Style'}
							</span>
						</button>

						<StyleDropdown
							isOpen={isStyleDropdownOpen}
							onClose={() => setIsStyleDropdownOpen(false)}
							selectedStyle={selectedStyle}
							onSelect={setSelectedStyle}
						/>
					</div>

					<button
						onClick={handleSubmit}
						disabled={!hasContent}
						className={cn(
							'flex h-9 w-9 items-center justify-center rounded-full transition-all',
							hasContent
								? 'bg-gradient-to-r from-blue-500 to-blue-500/75 text-white hover:from-blue-600 hover:to-blue-600/75 shadow-lg'
								: 'bg-black/10 text-black/40 cursor-not-allowed',
						)}
						aria-label="Send Prompt"
					>
						<Send className="h-4 w-4" />
					</button>
				</div>
			</div>
		</div>
	);
}

// PromptPage Component
export default function PromptPage() {
	// States
	const [generatedImage, setGeneratedImage] = useState<string | null>(null); // Image generated by API call
	const [isLoading, setIsLoading] = useState(false); // Is the image currently being generated?
	const [error, setError] = useState<string | null>(null); // For errors
	const [showModal, setShowModal] = useState(false); // For showing modal
	const [isLoginModalOpen, setIsLoginModalOpen] = useState(false);
	const [isPricingModalOpen, setIsPricingModalOpen] = useState(false);
	const { supabase, claims } = useAuth();
	const signedIn: boolean = !!claims;
	/// Functions
	// Generate image from prompt
	async function genInBackend([tatPrompt, style]: TattooPair) {
		setIsLoading(true);
		setError(null);

		try {
			// 1. Get user details to check authentication status
			const {
				data: { user },
			} = await supabase.auth.getUser();

			if (!user) {
				setIsLoginModalOpen(true);
				setIsLoading(false);
				return;
			}

			// 2. Query the profiles table to verify subscription/has_access status
			const { data: profile, error: profileError } = await supabase
				.from('profiles')
				.select('has_access')
				.eq('user_id', user.id)
				.setHeader('Cache-Control', 'no-cache')
				.maybeSingle();

			console.log('Current logged-in user ID:', user.id);
			console.log('Subscription check response:', { profile, error: profileError });

			if (profileError) {
				console.error('Error fetching user profile:', profileError);
				setError('Failed to verify subscription status. Please try again.');
				setShowModal(true); // Open the modal to show the error
				setIsLoading(false);
				return;
			}

			// If profile row doesn't exist or user doesn't have access, show the pricing modal
			if (!profile || profile.has_access !== true) {
				setIsPricingModalOpen(true);
				setIsLoading(false);
				return;
			}

			// 3. User is authenticated and has access, proceed with image generation
			setGeneratedImage(null);
			setShowModal(true); // Show the generation progress modal

			console.log(`Sending prompt to backend: ${tatPrompt}`);

			// Get the current session token
			const {
				data: { session },
			} = await supabase.auth.getSession();

			// Fetch call
			const response = await fetch(`${backendUrl}/generate-tattoo`, {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					...(session?.access_token && {
						Authorization: `Bearer ${session.access_token}`,
					}),
				},
				body: JSON.stringify({ prompt: tatPrompt, style: style }),
			});

			// Handle Network Errors
			if (!response.ok) {
				const errorData = await response.json();
				throw new Error(errorData.detail || 'Failed to connect to server');
			}

			// Receive Data
			const data = await response.json();

			if (data.success && data.imageBase64) {
				setGeneratedImage(data.imageBase64); // Save the Base64 string
			} else {
				throw new Error('No image returned from AI');
			}
		} catch (err: unknown) {
			console.error('Generation failed:', err);
			const errorMessage = err instanceof Error ? err.message : 'Something went wrong';
			setError(errorMessage);
			setShowModal(true); // Open the modal to show the error
		} finally {
			setIsLoading(false);
		}
	}

	// Animation variants for the staggered fade-up effect
	const fadeUpVariants = {
		hidden: { opacity: 0, y: 30 },
		visible: (i: number) => ({
			opacity: 1,
			y: 0,
			transition: {
				duration: 1,
				delay: 0.5 + i * 0.2,
				ease: [0.25, 0.4, 0.25, 1] as const,
			},
		}),
	};

	return (
		<Background>
			<div className="relative min-h-screen w-full flex items-center justify-center overflow-hidden bg-transparent">
				<Sidebar onLoginClick={() => setIsLoginModalOpen(true)} />

				{/* Main Content Container */}
				<div className="relative z-10 container mx-auto px-4 md:px-6">
					<div className="max-w-5xl mx-auto text-center">
						{/* Header Badge */}

						{/* Main Title */}
						<motion.div
							custom={1}
							variants={fadeUpVariants}
							initial="hidden"
							animate="visible"
						>
							{signedIn ? (
								<h1 className="text-4xl sm:text-6xl md:text-7xl lg:text-8xl font-bold mb-6 md:mb-8 tracking-tight">
									<span className="bg-clip-text text-transparent bg-gradient-to-b from-black/60 to-black">
										New tattoo idea?
									</span>
								</h1>
							) : (
								<h1 className="text-4xl sm:text-6xl md:text-7xl lg:text-8xl font-bold mb-6 md:mb-8 tracking-tight">
									<span className="bg-clip-text text-transparent bg-gradient-to-b from-black/60 to-black">
										Your Next Unique Tattoo
									</span>
								</h1>
							)}
						</motion.div>

						{/* Description Text */}
						<motion.div
							custom={2}
							variants={fadeUpVariants}
							initial="hidden"
							animate="visible"
						>
							<p className="text-base sm:text-lg md:text-xl text-black/60 mb-12 leading-relaxed font-light tracking-wide max-w-3xl mx-auto px-4">
								Transform your ideas into unique tattoo designs. Describe your
								vision, and our AI tattoo generator dreams up custom artwork
								tailored to your style.
							</p>
						</motion.div>

						{/* Interactive Prompt Input */}
						<motion.div
							custom={3}
							variants={fadeUpVariants}
							initial="hidden"
							animate="visible"
						>
							<PromptInput onSend={genInBackend} />
						</motion.div>

						{/* Popup with generated tattoo */}
						<GeneratedTattooDisplay
							imageStatus={generatedImage}
							errorStatus={error}
							loadingStatus={isLoading}
							isOpen={showModal}
							onClose={() => setShowModal(false)}
						/>

						<LoginModal
							isOpen={isLoginModalOpen}
							onClose={() => setIsLoginModalOpen(false)}
						/>

						<PricingModal
							isOpen={isPricingModalOpen}
							onClose={() => setIsPricingModalOpen(false)}
						/>

						{/* Footer Stats / Trust Indicators */}
						<motion.div
							custom={4}
							variants={fadeUpVariants}
							initial="hidden"
							animate="visible"
							className="mt-12 flex items-center justify-center gap-8 text-sm text-black/60"
						>
							<div className="flex items-center gap-2">
								<div className="w-2 h-2 rounded-full bg-green-500" />
								<span>100k+ Designs Created</span>
							</div>
						</motion.div>
					</div>
				</div>

				{/* Bottom Overlay for depth */}
				<div className="absolute inset-0 bg-gradient-to-t from-white/50 via-transparent to-white/50 pointer-events-none" />
			</div>
		</Background>
	);
}
