'use client';

import { motion } from 'framer-motion';
import {
	Sparkles,
	Send,
	Mic,
	Image as ImageIcon,
	Zap,
	Paintbrush,
} from 'lucide-react';
import { useEffect, useState, useRef } from 'react';
import { cn } from '@/lib/utils';
import { ElegantShape } from '@/components/ElegantShape';
import GeneratedTattooDisplay from './components/GeneratedTattooDisplay';
import StyleDropdown, { type TattooStyle } from '@/components/StyleDropdown';
import { useNavigate } from 'react-router-dom';
import { useAuth } from './AuthContext';
import LoginModal from './components/LoginModal';

type TattooPair = [string, TattooStyle];

// Props for the PromptInput component
interface PromptInputProps {
	onSend?: (data: TattooPair) => void;
	placeholder?: string;
}

// PromptInput Component
function PromptInput({
	onSend = () => {},
	placeholder = 'Describe your dream tattoo...',
}: PromptInputProps) {
	const [input, setInput] = useState('');
	const [isStyleDropdownOpen, setIsStyleDropdownOpen] = useState(false);
	const [selectedStyle, setSelectedStyle] =
		useState<TattooStyle>('Traditional');
	const textareaRef = useRef<HTMLTextAreaElement>(null);
	const MAX_CHARS = 500;

	const handleSubmit = () => {
		if (input.trim()) {
			onSend([input, selectedStyle]); // Get input
			setInput('');
			// Reset height after sending
			if (textareaRef.current) {
				textareaRef.current.style.height = 'auto';
			}
		}
	};

	const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
		if (e.key === 'Enter' && !e.shiftKey) {
			e.preventDefault();
			handleSubmit();
		}
	};

	// Auto-resize textarea based on content
	useEffect(() => {
		if (textareaRef.current) {
			textareaRef.current.style.height = 'auto';
			textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 200)}px`;
		}
	}, [input]);

	const hasContent = input.trim() !== '';

	return (
		<div className="w-full max-w-4xl mx-auto">
			<div className="relative bg-black/5 backdrop-blur-xl border border-black/20 rounded-3xl shadow-2xl shadow-black/10 transition-all duration-300">
				<div className="relative">
					{/* Text Area */}
					<textarea
						maxLength={MAX_CHARS}
						ref={textareaRef}
						value={input}
						onChange={(e) => setInput(e.target.value)}
						onKeyDown={handleKeyDown}
						placeholder={placeholder}
						className="w-full px-6 py-5 bg-transparent border-none outline-none resize-none text-black text-base leading-relaxed placeholder:text-black/40 min-h-[60px] max-h-[200px]"
						style={{ overflow: 'hidden' }}
					/>

					{/* Char counter for Text Area */}
					<div className="absolute bottom-2 right-2 text-xs text-black/40 pointer-events-none">
						{input.length}/{MAX_CHARS}
					</div>
				</div>

				{/* Input Actions Footer */}
				<div className="flex items-center justify-between px-4 py-3 border-t border-black/10">
					<div className="flex items-center gap-2 relative">
						<button
							type="button"
							onClick={() => setIsStyleDropdownOpen(true)}
							className={cn(
								'flex h-9 items-center justify-center gap-2 px-3 rounded-full transition-all',
								selectedStyle
									? 'bg-blue-50 text-blue-600 hover:bg-blue-100'
									: 'text-black/60 hover:text-black hover:bg-black/10',
							)}
							aria-label="Choose Style"
						>
							<Paintbrush className="h-4 w-4" />
							<span className="text-sm font-medium">
								{selectedStyle || 'Style'}
							</span>
						</button>

						<StyleDropdown
							isOpen={isStyleDropdownOpen}
							onClose={() => setIsStyleDropdownOpen(false)}
							selectedStyle={selectedStyle}
							onSelect={setSelectedStyle}
						/>

						<button
							type="button"
							className="flex h-9 w-9 items-center justify-center rounded-full text-black/60 hover:text-black hover:bg-black/10 transition-all"
							aria-label="Upload Image"
						>
							<ImageIcon className="h-5 w-5" />
						</button>
						<button
							type="button"
							className="flex h-9 w-9 items-center justify-center rounded-full text-black/60 hover:text-black hover:bg-black/10 transition-all"
							aria-label="Use Microphone"
						>
							<Mic className="h-5 w-5" />
						</button>
					</div>

					<button
						onClick={handleSubmit}
						disabled={!hasContent}
						className={cn(
							'flex h-9 w-9 items-center justify-center rounded-full transition-all',
							hasContent
								? 'bg-gradient-to-r from-blue-500 to-blue-500/75 text-white hover:from-blue-600 hover:to-blue-600/75 shadow-lg'
								: 'bg-black/10 text-black/40 cursor-not-allowed',
						)}
						aria-label="Send Prompt"
					>
						<Send className="h-4 w-4" />
					</button>
				</div>
			</div>
		</div>
	);
}

// PromptPage Component
export default function PromptPage() {
	// States
	const [generatedImage, setGeneratedImage] = useState<string | null>(null); // Image generated by API call
	const [isLoading, setIsLoading] = useState(false); // Is the image currently being generated?
	const [error, setError] = useState<string | null>(null); // For errors
	const [showModal, setShowModal] = useState(false); // For showing modal
	const [isLoginModalOpen, setIsLoginModalOpen] = useState(false);
	const navigate = useNavigate();
	const { claims, supabase } = useAuth();

	/// Functions
	// Generate image from prompt
	async function genInBackend(tatPrompt: string) {
		setIsLoading(true);
		setError(null);
		setGeneratedImage(null); // Clear previous image
		setShowModal(true); // Show modal

		try {
			console.log(`Sending prompt to backend: ${tatPrompt}`);

			// Fetch call
			const response = await fetch('http://localhost:8000/generate-tattoo', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({ prompt: tatPrompt }),
			});

			// Handle Network Errors
			if (!response.ok) {
				const errorData = await response.json();
				throw new Error(errorData.error || 'Failed to connect to server');
			}

			// Receive Data
			const data = await response.json();

			console.log(data);

			if (data.success && data.imageBase64) {
				setGeneratedImage(data.imageBase64); // Save the Base64 string
			} else {
				throw new Error('No image returned from AI');
			}
		} catch (err: any) {
			console.error('Generation failed:', err);
			setError(err.message || 'Something went wrong');
		} finally {
			setIsLoading(false);
		}
	}

	// Animation variants for the staggered fade-up effect
	const fadeUpVariants = {
		hidden: { opacity: 0, y: 30 },
		visible: (i: number) => ({
			opacity: 1,
			y: 0,
			transition: {
				duration: 1,
				delay: 0.5 + i * 0.2,
				ease: [0.25, 0.4, 0.25, 1] as const,
			},
		}),
	};
	console.log(claims);

	return (
		<div className="relative min-h-screen w-full flex items-center justify-center overflow-hidden bg-white">
			{/* Login Button */}
			{!claims && (
				<div className="absolute top-6 left-6 z-50">
					<button
						onClick={() => setIsLoginModalOpen(true)}
						className="px-6 py-2.5 rounded-full bg-black/5 hover:bg-black/10 text-black font-medium transition-all duration-300 backdrop-blur-sm border border-black/10 shadow-sm"
					>
						Login
					</button>
				</div>
			)}

			{/* Background Ambient Gradient */}
			<div className="absolute inset-0 bg-gradient-to-br from-purple-500/[0.05] via-transparent to-pink-500/[0.05] blur-3xl" />

			{/* Floating Background Shapes */}
			<div className="absolute inset-0 overflow-hidden">
				<ElegantShape
					delay={0.3}
					width={250}
					height={250}
					rotate={12}
					className="left-[-10%] md:left-[2%] top-[15%] md:top-[2%]"
					illustration={3}
				/>

				<ElegantShape
					delay={0.5}
					width={250}
					height={250}
					rotate={-15}
					className="right-[50%] md:right-[7%] top-[70%] md:top-[65%]"
					illustration={1}
				/>

				<ElegantShape
					delay={0.4}
					width={220}
					height={220}
					rotate={22}
					className="left-[5%] md:left-[35%] bottom-[5%] md:bottom-[-2%]"
					illustration={4}
				/>

				<ElegantShape
					delay={0.6}
					width={400}
					height={400}
					rotate={20}
					className="right-[15%] md:right-[-3%] top-[10%] md:top-[-8%]"
					illustration={2}
				/>

				<ElegantShape
					delay={0.6}
					width={400}
					height={400}
					rotate={-25}
					className="left-[10%] md:left-[3%] bottom-[10%] md:bottom-[-2%]"
					illustration={5}
				/>
			</div>

			{/* Main Content Container */}
			<div className="relative z-10 container mx-auto px-4 md:px-6">
				<div className="max-w-5xl mx-auto text-center">
					{/* Header Badge */}

					{/* Main Title */}
					<motion.div
						custom={1}
						variants={fadeUpVariants}
						initial="hidden"
						animate="visible"
					>
						<h1 className="text-4xl sm:text-6xl md:text-7xl lg:text-8xl font-bold mb-6 md:mb-8 tracking-tight">
							<span className="bg-clip-text text-transparent bg-gradient-to-b from-black/60 to-black">
								Your Next
							</span>
							<br />
							<span className="bg-clip-text text-transparent bg-gradient-to-b from-black to-black/60">
								<span className="bg-clip-text text-transparent bg-gradient-to-b from-blue-500/75 to-blue-500">
									Unique
								</span>{' '}
								Tattoo
							</span>
						</h1>
					</motion.div>

					{/* Description Text */}
					<motion.div
						custom={2}
						variants={fadeUpVariants}
						initial="hidden"
						animate="visible"
					>
						<p className="text-base sm:text-lg md:text-xl text-black/60 mb-12 leading-relaxed font-light tracking-wide max-w-3xl mx-auto px-4">
							Transform your ideas into unique tattoo designs. Describe your
							vision, and our AI tattoo generator dreams up custom artwork
							tailored to your style.
						</p>
					</motion.div>

					{/* Interactive Prompt Input */}
					<motion.div
						custom={3}
						variants={fadeUpVariants}
						initial="hidden"
						animate="visible"
					>
						<PromptInput onSend={genInBackend} />
					</motion.div>

					{/* Popup with generated tattoo */}
					<GeneratedTattooDisplay
						imageStatus={generatedImage}
						errorStatus={error}
						loadingStatus={isLoading}
						isOpen={showModal}
						onClose={() => setShowModal(false)}
					/>

					<LoginModal
						isOpen={isLoginModalOpen}
						onClose={() => setIsLoginModalOpen(false)}
					/>

					{/* Footer Stats / Trust Indicators */}
					<motion.div
						custom={4}
						variants={fadeUpVariants}
						initial="hidden"
						animate="visible"
						className="mt-12 flex items-center justify-center gap-8 text-sm text-black/60"
					>
						<div className="flex items-center gap-2">
							<div className="w-2 h-2 rounded-full bg-green-500" />
							<span>100k+ Designs Created</span>
						</div>
					</motion.div>
				</div>
			</div>

			{/* Bottom Overlay for depth */}
			<div className="absolute inset-0 bg-gradient-to-t from-white/50 via-transparent to-white/50 pointer-events-none" />
		</div>
	);
}
